### ISSUE TITLE
xray-license.lic过期

### ISSUE THREAD

**Issue by itry02** [NHPT/Xray_Cracked#1]
┌──(kali㉿kali)-[~/桌面/xray1.9.1]
└─$ ./xray_linux_amd64
this license is expired, expiration time is 2022-08-02 20:00:00
                                                                                                                      
┌──(kali㉿kali)-[~/桌面/xray1.9.1]
└─$ date +"%Y-%m-%d"
2022-08-18

**Comment by NHPT** [comment]
Try again!

**Comment by aba666666** [comment]
又过期了
