### ISSUE TITLE
m2还是爆错

### ISSUE THREAD

**Issue by gusechuisheng** [NHPT/Xray_Cracked#10]
<img width="368" alt="截屏2023-03-20 23 59 13" src="https://user-images.githubusercontent.com/49669724/226398436-40e6a8ae-5dee-427d-9db5-7b7ec5113d18.png">
<img width="469" alt="截屏2023-03-20 23 59 39" src="https://user-images.githubusercontent.com/49669724/226398450-80dbc281-23eb-41cb-a5c7-d0920b7adf71.png">

**Comment by NHPT** [comment]
试试amd64的

**Comment by gusechuisheng** [comment]
> 试试amd64的

好了
