### ISSUE TITLE
MacOS AMD64从老版本更新到13.3.1 (22E261)后报错

### ISSUE THREAD

**Issue by ThestaRY7** [NHPT/Xray_Cracked#12]
没事真不要更新，更新完之后py2没了，然后底层框架好像也有变动。
更新成13.3.1 (22E261)后，运行报错：
segmentation fault。
根据Newbing的解决方法：
[根据网络搜索结果，macos segmentation fault是一个常见的错误，可能有多种原因](https://stackoverflow.com/questions/64842404/matplotlib-segmentation-fault-mac-os-11big-sur)[1](https://stackoverflow.com/questions/64842404/matplotlib-segmentation-fault-mac-os-11big-sur)[2](https://github.com/nodejs/node/issues/44219)[3](https://github.com/xmrig/xmrig/issues/3183)。一些可能的解决方案是：

[更新你的软件或库，例如matplotlib](https://stackoverflow.com/questions/64842404/matplotlib-segmentation-fault-mac-os-11big-sur)[1](https://stackoverflow.com/questions/64842404/matplotlib-segmentation-fault-mac-os-11big-sur)[或nodejs](https://github.com/nodejs/node/issues/44219)[2](https://github.com/nodejs/node/issues/44219)，到最新的版本。
检查你的代码是否有内存泄漏或指针错误，尤其是如果你使用了C或C++等低级语言。
使用调试工具，例如gdb或lldb，来定位错误发生的位置和原因。
[如果你使用了M1芯片的MacBook，可能需要重新编译你的程序或库，以适应不同的架构](https://github.com/xmrig/xmrig/issues/3183)[3](https://github.com/xmrig/xmrig/issues/3183)。
希望这些信息对你有帮助。如果你还有其他问题，请随时提出。

同事的解决方法是重新编译，如Go build再本机编译后即可用，但我没源码。。。

**Comment by NHPT** [comment]
星球里有过程，代码贴出来怕收到文件

**Comment by chenchenhen6** [comment]
<img width="578" alt="image" src="https://user-images.githubusercontent.com/35289748/233893675-f6c2e28d-85a2-42a3-b294-2289bc783a61.png">
我的也是这样

**Comment by chenchenhen6** [comment]
问题解决了，我使用upx -d xray
<img width="638" alt="image" src="https://user-images.githubusercontent.com/35289748/233915503-e49c0e15-d617-4e85-b315-e3cbbc05862b.png">

**Comment by NHPT** [comment]
牛哇，原来是压缩导致的问题

**Comment by ThestaRY7** [comment]
牛批哇，我upx -d 1.9.4没问题，但1.9.8会显示：upx: xray: CantUnpackException: header corrupted 2

**Comment by chenchenhen6** [comment]
brew update   brew upgrade

**Comment by chenchenhen6** [comment]
更新下upx试试

**Comment by NHPT** [comment]
不应该啊，我就upx压缩的，刚试了试可以解压的呀，用最新版upx试试

**Comment by ThestaRY7** [comment]
好了，我从UPX 3.96更新到UPX 4.0.2，可以了。
