### ISSUE TITLE
mac arm 不能运行

### ISSUE THREAD

**Issue by cqrlhz** [NHPT/Xray_Cracked#13]
![捕获](https://user-images.githubusercontent.com/63200706/233943701-e98f7c1f-291c-48ec-a392-46a7466c6d9c.PNG)

**Comment by NHPT** [comment]
chmod 755 xxx

**Comment by NHPT** [comment]
隐私与安全设置允许

**Comment by gloomytime** [comment]
chmod给了权限之后运行也是killed，没有提示隐私与安全需要允许，只能用amd64版本。系统是12.6.5
