### ISSUE TITLE
Xray-arm64无响应

### ISSUE THREAD

**Issue by JiuZero** [NHPT/Xray_Cracked#16]
我尝试了所有版本的xray-arm64-crack，均无响应![IMG_20230709_182521.jpg](https://github.com/NHPT/Xray_Cracked/assets/109419998/2e7cbd72-391f-4912-b501-fe4b815a0c57)

**Comment by JiuZero** [comment]
我想这可能是xray对termux的兼容问题，我在使用xray官方编译文件时得到了报错。可能我需要在proot容器上使用它。
![IMG_20230709_184139.jpg](https://github.com/NHPT/Xray_Cracked/assets/109419998/360fc628-00f6-463e-9215-0b3608233fee)

**Comment by lyangdn** [comment]
uname -r 查看一下是不是arm架构的
