### ISSUE TITLE
Mac 运行失败（darwin_arm64 of  linux_arm64）

### ISSUE THREAD

**Issue by badboycxcc** [NHPT/Xray_Cracked#18]
![截屏2023-09-30 上午7 24 33](https://github.com/NHPT/Xray_Cracked/assets/72059221/bc50bce7-60b3-489e-bf18-e2686bbf0a32)
![截屏2023-09-30 上午7 23 14](https://github.com/NHPT/Xray_Cracked/assets/72059221/12f06289-fc5d-481d-91d4-e40a22b13b8d)

**Comment by NHPT** [comment]
Stupid ，多看看已关闭的同类型的issues ，OK?
