### ISSUE TITLE
mac运行killed

### ISSUE THREAD

**Issue by Le0T007** [NHPT/Xray_Cracked#19]
<img width="317" alt="image" src="https://github.com/NHPT/Xray_Cracked/assets/37946922/fcd5d629-030c-4a8b-a2f3-9203a5c1f679">

**Comment by shanon00** [comment]
upx -d 之后也是，报错啊

**Comment by NHPT** [comment]
不应该啊  看看架构选对了没

**Comment by NHPT** [comment]
噢对  upx版本   你看看其它的issues
