### ISSUE TITLE
更新macos15后使用报错

### ISSUE THREAD

**Issue by Silence566** [NHPT/Xray_Cracked#20]
<img width="858" alt="image" src="https://github.com/user-attachments/assets/e231c237-99fc-4c41-80b4-c1048664f54c">

**Comment by ohnoa** [comment]
同样的问题，求解

**Comment by NHPT** [comment]
upx -d 试了没  多看看其它issues

**Comment by ohnoa** [comment]
没注意有关闭的 issue，谢谢，解决了！
