### ISSUE TITLE
求linux arm64架构的破解版xray

### ISSUE THREAD

**Issue by JiuZero** [NHPT/Xray_Cracked#6]
求师傅提供linux_arm64_xray破解文件，如果师傅没有环境，我可以为大师傅测试～其实手机就是arm64架构的，可以装个termux运行xray

**Comment by NHPT** [comment]
https://www.aliyundrive.com/s/JjasKe7uqXW
你试试

**Comment by JiuZero** [comment]
看起来它好像能够很好地在arm64_linux架构中运行【测试环境termux&nethunter】
![image](https://user-images.githubusercontent.com/109419998/218072833-6a570af3-ca8b-4a0f-9e0e-9af164ef987e.jpeg)

**Comment by JiuZero** [comment]
十分感谢～

**Comment by NHPT** [comment]
ok
