### ISSUE TITLE
./xray_darwin_amd64 Segmentation fault: 11

### ISSUE THREAD

**Issue by qooloop** [NHPT/Xray_Cracked#7]
./xray_darwin_amd64
chmod +x给了可执行权限，但是运行报错：
Segmentation fault: 11

**Comment by NHPT** [comment]
你自己排查吧，看下架构是不是MAC amd64的

**Comment by Rica123** [comment]
我好像也是这个问题

**Comment by zzqsmile** [comment]
我的也是这个问题 电脑是amd的，不是arm
