### ISSUE TITLE
xray_darwin_arm64运行报错

### ISSUE THREAD

**Issue by zqlzs** [NHPT/Xray_Cracked#8]
![image](https://user-images.githubusercontent.com/83104031/219398650-72ca736d-8df2-42c6-8d97-50c8803c2ed5.png)

**Comment by NHPT** [comment]
![](https://github.com/NHPT/Xray_Cracked/blob/main/img/1.png)
![](https://github.com/NHPT/Xray_Cracked/blob/main/img/2.png)
![](https://github.com/NHPT/Xray_Cracked/blob/main/img/3.png)
![](https://github.com/NHPT/Xray_Cracked/blob/main/img/4.png)

**Comment by NHPT** [comment]
https://github.com/NHPT/Xray_Cracked/blob/main/README.md

**Comment by GaoZzr** [comment]
开启任何来源后依然显示zsh killed xxx

**Comment by gusechuisheng** [comment]
> https://github.com/NHPT/Xray_Cracked/blob/main/README.md

你的成功了吗

**Comment by UsersDisabled** [comment]
UTF-8 错误
<img width="290" alt="image" src="https://user-images.githubusercontent.com/71540153/233882343-27367dc9-3a4a-4f44-af93-0f916b273701.png">

**Comment by NHPT** [comment]
chmod
