### ISSUE TITLE
证书到期时间2022-08-03 08:00:00

### ISSUE THREAD

**Issue by chessan** [NHPT/Xray_Cracked#9]
![image](https://user-images.githubusercontent.com/61547727/222646681-14eec08d-37eb-42e1-a1c9-7cfed7dffb0d.png)

**Comment by NHPT** [comment]
只是这样显示而已，又不影响使用，license is valid
![image](https://user-images.githubusercontent.com/42366434/222647496-14c8ac83-22ad-461f-bc30-0dbaea787cd6.png)
